<div align='center' >

# 异常

</div>

> [程序练习](https://github.com/Nicolas-gaofeng/Salute_Python/blob/main/code/basic/python_exception/python_exception.py)

异常处理也就是处理异常，那么我们首先要知道什么是异常？

异常是错误发生的信号，程序一旦出错，如果程序中还没有相应的处理机制，那么该错误就会产生一个异常抛出来，程序的运行也随之终止

## 1. 异常的概念

- 程序在运行时，如果 Python 解释器遇到到一个错误，会停止程序的执行，并且提示一些错误信息，这就是异常
- 程序停止执行并且提示错误信息这个动作，我们通常称之为：抛出(raise)异常

![001_异常示意图](https://gitee.com/zgf1366/pic_store/raw/master/img/20210120185107.png)

- 程序开发时，很难将 所有的特殊情况都处理的面面俱到，通过异常捕获可以针对突发事件做集中的处理，从而保证程序的稳定性和健壮性

## 2. 捕获异常

1. 简单的捕获异常语法

- 在程序开发中，如果对某些代码的执行不能确定是否正确，可以增加 try(尝试) 来捕获异常
- 捕获异常最简单的语法格式：

```python
try:
    尝试执行的代码
except:
    出现错误的处理
```

- try尝试，下方编写要尝试代码，不确定是否能够正常执行的代码
- except如果不是，下方编写尝试失败的代码

简单异常捕获演练 —— 要求用户输入整数

```python
try:
    # 提示用户输入一个数字
    num = int(input("请输入数字："))
except:
    print("请输入正确的数字")
```

2. 错误类型捕获

- 在程序执行时，可能会遇到不同类型的异常，并且需要针对不同类型的异常，做出不同的响应，这个时候，就需要捕获错误类型了
- 语法如下：

```python
try:
    # 尝试执行的代码
    pass
except 错误类型1:
    # 针对错误类型1，对应的代码处理
    pass
except (错误类型2, 错误类型3):
    # 针对错误类型2 和 3，对应的代码处理
    pass
except Exception as result:
    print("未知错误 %s" % result)
```

- 当 Python 解释器 抛出异常时，最后一行错误信息的第一个单词，就是错误类型

异常类型捕获演练 —— 要求用户输入整数

**需求**

1. 提示用户输入一个整数
2. 使用 `8` 除以用户输入的整数并且输出

```python
try:
    num = int(input("请输入整数："))
    result = 8 / num
    print(result)
except ValueError:
    print("请输入正确的整数")
except ZeroDivisionError:
    print("除 0 错误")
except Exception as result:
    print("未知错误 %s" % result)
else:
    print("正常执行")
finally:
    print("执行完成，但是不保证正确")
```

捕获未知错误

- 在开发时，要预判到所有可能出现的错误，还是有一定难度的
- 如果希望程序无论出现任何错误，都不会因为 Python 解释器抛出异常而被终止，可以再增加一个except

- else 只有在没有异常时才会执行的代码
- finally 无论是否有异常，都会执行的代码

## 3. 异常的传递

- 异常的传递 —— 当 函数/方法执行出现异常，会将异常传递给 函数/方法 的调用一方
- 如果传递到主程序，仍然没有异常处理，程序才会被终止

**提示**

- 在开发中，可以在主函数中增加异常捕获
- 而在主函数中调用的其他函数，只要出现异常，都会传递到主函数的异常捕获中
- 这样就不需要在代码中，增加大量的异常捕获，能够保证代码的整洁

**需求**

1. 定义函数 demo1() 提示用户输入一个整数并且返回
2. 定义函数 demo2() 调用 demo1()
3. 在主程序中调用 demo2()

```python
def demo1():
    return int(input("请输入一个整数："))

def demo2():
    return demo1()

try:
    print(demo2())
except ValueError:
    print("请输入正确的整数")
except Exception as result:
    print("未知错误 %s" % result)
```

## 4. 抛出 raise 异常

1. 应用场景

- 在开发中，除了代码执行出错 Python 解释器会抛出异常之外
- 还可以根据应用程序特有的业务需求主动抛出异常

**示例**

- 提示用户输入密码，如果长度少于 8，抛出异常

![024_自定义异常](https://gitee.com/zgf1366/pic_store/raw/master/img/20210120185140.png)

**注意**

- 当前函数只负责提示用户输入密码，如果密码长度不正确，需要其他的函数进行额外处理
- 因此可以抛出异常，由其他需要处理的函数捕获异常

2. 抛出异常

- Python 中提供了一个 Exception 异常类
- 在开发时，如果满足特定业务需求时，希望抛出异常，可以：
  1. 创建一个 `Exception` 的对象
  2. 使用 `raise` 关键字抛出异常对象

**需求**

- 定义 input_password 函数，提示用户输入密码
- 如果用户输入长度 < 8，抛出异常
- 如果用户输入长度 >=8，返回输入的密码

```python
def input_password():
    # 1. 提示用户输入密码
    pwd = input("请输入密码：")
    # 2. 判断密码长度，如果长度 >= 8，返回用户输入的密码
    if len(pwd) >= 8:
        return pwd
    # 3. 密码长度不够，需要抛出异常
    # 1> 创建异常对象 - 使用异常的错误信息字符串作为参数
    ex = Exception("密码长度不够")
    # 2> 抛出异常对象
    raise ex
try:
    user_pwd = input_password()
    print(user_pwd)
except Exception as result:
    print("发现错误：%s" % result)
```

### 4.1 主动触发异常

#### 4.1.1 raise 主动触发异常

我们希望能够主动触发异常，来对使用者进行一定的限制。

```python
print(TypeError)  # TypeError是一个类
obj = TypeError("类型错误")  # 这其实就是实例化对象的过程
print(obj)
class People:
    def __init__(self, name):
        if not isinstance(name, str):
            raise TypeError('用户名 %s 必须是str类型' % name)
        self.name = name
p = People(123)
```

#### 4.1.2 assert 断言

试想一个场景，假如程序执行了很多代码到了第300行代码，而第300行代码得出的变量值是否为空，将关系到下面的代码是否运行，没有断言之前我们一般会这么处理

```python
print('part1........')
print('part1........')
print('part1........')
print('part1........')
print('part1........')
students = ['Albert', 'Harden', 'Curry', 'Wade']
students = []
if len(students) <= 0:
    raise TypeError  # 这里也可以不传参数
print('part2.........')
print('part2.........')
print('part2.........')
print('part2.........')
print('part2.........')
print('part2.........')
```

使用断言：

```python
print('part1........')
print('part1........')
print('part1........')
print('part1........')
print('part1........')
students = ['Albert', 'Harden', 'Curry', 'Wade']
# students = []
# if len(students) <= 0:
#     raise TypeError  # 这里也可以不传参数
assert len(students) > 0
print('part2.........')
print('part2.........')
print('part2.........')
print('part2.........')
print('part2.........')
print('part2.........')
```

#### 4.1.3 自定义异常

异常也就是一个类，那么我们当然可以自定义

```python
class RegisterError(BaseException):  # 需要继承这个异常的基类BaseException
    def __init__(self,massage,username):
        self.massage=massage
        self.username=username
    def __str__(self):  # 自定义对象的打印格式
        return '<%s：%s>' %(self.username,self.massage)
print(RegisterError)

# 1 初始化对象
obj = RegisterError('注册失败','Albert')
# 2 打印这个对象
print(obj)

# 下面这行代码就相当于先初始化对象，再打印这个对象
raise RegisterError('注册失败','Albert')
```